name: Devops
on:
  push:
  workflow_dispatch:
jobs:
Run-action:
   runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
       - name: Run script file
      run: |
         chmod +x ./bash.sh
         ./bash.sh
      shell: bash
