name: Devops
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      run: |
         chmod +x ./.github/workflows/bash.sh
         ./.github/workflows/bash.sh
      shell: bash
